### ISSUE TITLE
关于运行main_test .py产生图的问题？

### ISSUE THREAD

**Issue by Jb-byte** [le-liang/MARLspectrumSharingV2X#3]
梁老师，您好！根据阅读README.md,运行main_test.py可以直接得到论文中的图3和图4，这边我运行结束得到程序所生成的mat文件，对于图3和图4是根据mat文件在MATLB中生成还是在python中将其转换成csv或excel文件来进行画图？所以，想请教一下梁老师。谢谢！

**Comment by le-liang** [comment]
设置不同的 N (x 1060 Bytes)，运行之后会在Data.txt里存相应的 V2I sum rate 和 V2V packet delivery rate，可以汇总结果然后在 MATLAB 里画图。.mat文件里存的是测试阶段每个 step的 demand等值，用来画图6和7的。

**Comment by Jb-byte** [comment]
好的，谢谢梁老师

**Comment by ZXHL** [comment]
您好！请问下，您跑main_test.py模块时有没有出现错误，例如
![image](https://user-images.githubusercontent.com/48380516/87750867-294aaf80-c82f-11ea-8129-404ca72617c4.png)

**Comment by ZXHL** [comment]
您好！请问下，您跑main_test.py模块时有没有出现错误，例如
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key batch_normalization_2/beta/RMSProp not found in checkpoint
	 [[node save/RestoreV2 (defined at E:MARLspectrumSharingV2X-master/main_test.py:174)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by le-liang** [comment]
> 您好！请问下，您跑main_test.py模块时有没有出现错误，例如
> NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key batch_normalization_2/beta/RMSProp not found in checkpoint
> [[node save/RestoreV2 (defined at E:MARLspectrumSharingV2X-master/main_test.py:174) = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Thanks for bringing up the issue, which is due to a previous update in setting up DQN output that contradicts the stored model. Resolved now.

**Comment by ZXHL** [comment]
非常感谢，梁老师的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "le-liang/MARLspectrumSharingV2X"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 凌晨1:17
收件人:&nbsp;"le-liang/MARLspectrumSharingV2X"<MARLspectrumSharingV2X@noreply.github.com&gt;;
抄送:&nbsp;"Gentle smile"<842708795@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [le-liang/MARLspectrumSharingV2X] 关于运行main_test .py产生图的问题？ (#3)





  
您好！请问下，您跑main_test.py模块时有没有出现错误，例如
 NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
 
Key batch_normalization_2/beta/RMSProp not found in checkpoint
 [[node save/RestoreV2 (defined at E:MARLspectrumSharingV2X-master/main_test.py:174) = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
  
Thanks for bringing up the issue, which is due to a previous update in setting up DQN output that contradicts the stored model. Resolved now.
